package ru.lagarnikov.easyenglish13

import android.content.res.Resources
import ru.lagarnikov.easyenglish13.view.RecyclerViewAdapterAndData.DataAllTheme
import ru.lagarnikov.easyenglish13.view.RecyclerViewAdapterAndData.DataOneTheme

fun getAllThemeData():ArrayList<DataAllTheme>{
    var dataTheme= arrayListOf<DataAllTheme>()
    dataTheme.add(DataAllTheme(R.string.themeMain1,R.string.themeNumber1, R.drawable.ic_human_a))
    dataTheme.add(DataAllTheme(R.string.themeMain2,R.string.themeNumber2, R.drawable.health_aa))
    dataTheme.add(DataAllTheme(R.string.themeMain3,R.string.themeNumber3, R.drawable.ic_family_a))
    dataTheme.add(DataAllTheme(R.string.themeMain4,R.string.themeNumber4, R.drawable.ic_house_a))
    dataTheme.add(DataAllTheme(R.string.themeMain5,R.string.themeNumber5, R.drawable.ic_travel_a))
    dataTheme.add(DataAllTheme(R.string.themeMain6,R.string.themeNumber6, R.drawable.ic_size_a))
    dataTheme.add(DataAllTheme(R.string.themeMain7,R.string.themeNumber7, R.drawable.ic_food_a))
    dataTheme.add(DataAllTheme(R.string.themeMain8,R.string.themeNumber8, R.drawable.ic_natura_a))
    dataTheme.add(DataAllTheme(R.string.themeMain9,R.string.themeNumber9, R.drawable.ic_colore_a))
    dataTheme.add(DataAllTheme(R.string.themeMain10,R.string.themeNumber10, R.drawable.ic_clothes_a))
    dataTheme.add(DataAllTheme(R.string.themeMain11,R.string.themeNumber11, R.drawable.ic_animal_a))
    dataTheme.add(DataAllTheme(R.string.themeMain12,R.string.themeNumber12, R.drawable.ic_act_a))


    return dataTheme
}


//Ораньжевые фотки на фрагмент выбора темы, когда тема изучается(или изучилась) она ораньжеветт
fun getOrangeFoto():ArrayList<Int>{
    val dataOrangeFoto= arrayListOf<Int>()
    dataOrangeFoto.add(R.drawable.ic_humana_or)
    dataOrangeFoto.add(R.drawable.ic_healtha_or)
    dataOrangeFoto.add(R.drawable.ic_familya_or)
    dataOrangeFoto.add(R.drawable.ic_housea_or)
    dataOrangeFoto.add(R.drawable.ic_travela_or)
    dataOrangeFoto.add(R.drawable.ic_sizea_or)
    dataOrangeFoto.add(R.drawable.ic_fooda_or)
    dataOrangeFoto.add(R.drawable.ic_naturaa_or)
    dataOrangeFoto.add(R.drawable.ic_colorea_or)
    dataOrangeFoto.add(R.drawable.ic_clothesa_or)
    dataOrangeFoto.add(R.drawable.ic_animala_or)
    dataOrangeFoto.add(R.drawable.ic_acta_or)

    return dataOrangeFoto
}

//Ораньжевые фотки на TopFragment
fun getOrangeFotoTopFragment():ArrayList<Int>{
    val dataOrangeFoto= arrayListOf<Int>()
    dataOrangeFoto.add(R.drawable.ic_human_c)
    dataOrangeFoto.add(R.drawable.health_c)
    dataOrangeFoto.add(R.drawable.ic_family_c)
    dataOrangeFoto.add(R.drawable.ic_house_c)
dataOrangeFoto.add(R.drawable.ic_travel_c)
dataOrangeFoto.add(R.drawable.ic_size_c)
dataOrangeFoto.add(R.drawable.ic_food_c)
dataOrangeFoto.add(R.drawable.ic_natura_c)
dataOrangeFoto.add(R.drawable.ic_colore_c)
dataOrangeFoto.add(R.drawable.ic_clothes_c)
dataOrangeFoto.add(R.drawable.ic_animal_c)
dataOrangeFoto.add(R.drawable.ic_act_c)

return dataOrangeFoto
}

fun getOrangeFotoTopFragmentMInimum():ArrayList<Int>{
    val dataOrangeFoto= arrayListOf<Int>()
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)
    dataOrangeFoto.add(R.drawable.need_delete)

    return dataOrangeFoto
}

fun getUpFotoThemeWord(themeName:String, resources: Resources):Int{
    when(themeName){
        resources.getString(R.string.themeMain1).toUpperCase() -> return R.drawable.ic_human_b_a
        resources.getString(R.string.themeMain2).toUpperCase() -> return R.drawable.ic_health_b_a
        resources.getString(R.string.themeMain3).toUpperCase() -> return R.drawable.ic_family_b_a
        resources.getString(R.string.themeMain4).toUpperCase() -> return R.drawable.ic_house_b_a
        resources.getString(R.string.themeMain5).toUpperCase() -> return R.drawable.ic_travel_b_a
        resources.getString(R.string.themeMain6).toUpperCase() -> return R.drawable.ic_size_b_a
        resources.getString(R.string.themeMain7).toUpperCase() -> return R.drawable.ic_food_b_a
        resources.getString(R.string.themeMain8).toUpperCase() -> return R.drawable.ic_natura_b_a
        resources.getString(R.string.themeMain9).toUpperCase() -> return R.drawable.ic_colore_b_a
        resources.getString(R.string.themeMain10).toUpperCase() -> return R.drawable.ic_clothes_b_a
        resources.getString(R.string.themeMain11).toUpperCase() -> return R.drawable.ic_animal_b_a
        resources.getString(R.string.themeMain12).toUpperCase() -> return R.drawable.ic_act_b_a
    }

    return 0



}

fun getDownFotoThemeWord(themeName:String, resources: Resources):Int{
    when(themeName){
        resources.getString(R.string.themeMain1).toUpperCase() -> return R.drawable.ic_human_b_b
        resources.getString(R.string.themeMain2).toUpperCase() -> return R.drawable.ic_health_b_b
        resources.getString(R.string.themeMain3).toUpperCase() -> return R.drawable.ic_family_b_b
        resources.getString(R.string.themeMain4).toUpperCase() -> return R.drawable.ic_house_b_b
        resources.getString(R.string.themeMain5).toUpperCase() -> return R.drawable.ic_travel_b_b
        resources.getString(R.string.themeMain6).toUpperCase() -> return R.drawable.ic_size_b_b
        resources.getString(R.string.themeMain7).toUpperCase() -> return R.drawable.ic_food_b_b
        resources.getString(R.string.themeMain8).toUpperCase() -> return R.drawable.ic_natura_b_b
        resources.getString(R.string.themeMain9).toUpperCase() -> return R.drawable.ic_colore_b_b
        resources.getString(R.string.themeMain10).toUpperCase() -> return R.drawable.ic_clothes_b_b
        resources.getString(R.string.themeMain11).toUpperCase() -> return R.drawable.ic_animal_b_b
        resources.getString(R.string.themeMain12).toUpperCase() -> return R.drawable.ic_act_b_b
    }

    return 0



}

fun getOneThemeData(themeName:String, resources: Resources):ArrayList<DataOneTheme>{
    when(themeName){
        resources.getString(R.string.themeMain1).toUpperCase() -> return get1ThemeData()
        resources.getString(R.string.themeMain2).toUpperCase() -> return get2ThemeData()
        resources.getString(R.string.themeMain3).toUpperCase() -> return get3ThemeData()
        resources.getString(R.string.themeMain4).toUpperCase() -> return get4ThemeData()
        resources.getString(R.string.themeMain5).toUpperCase() -> return get5ThemeData()
        resources.getString(R.string.themeMain6).toUpperCase() -> return get6ThemeData()
        resources.getString(R.string.themeMain7).toUpperCase() -> return get7ThemeData()
        resources.getString(R.string.themeMain8).toUpperCase() -> return get8ThemeData()
        resources.getString(R.string.themeMain9).toUpperCase() -> return get9ThemeData()
        resources.getString(R.string.themeMain10).toUpperCase() -> return get10ThemeData()
        resources.getString(R.string.themeMain11).toUpperCase() -> return get11ThemeData()
        resources.getString(R.string.themeMain12).toUpperCase() -> return get12ThemeData()
    }

    return get1ThemeData()



}

private fun get1ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("man"," мужчина"))
    dataTheme.add(DataOneTheme("woman","женщина"))
    dataTheme.add(DataOneTheme("body","тело"))
    dataTheme.add(DataOneTheme("head","голова"))
    dataTheme.add(DataOneTheme("shoulder","плечо"))
    dataTheme.add(DataOneTheme("hand","рука "))
    dataTheme.add(DataOneTheme("elbow","локоть"))
    dataTheme.add(DataOneTheme("chest","грудная клетка"))
    dataTheme.add(DataOneTheme("stomach","живот"))
    dataTheme.add(DataOneTheme("back","спина"))
    dataTheme.add(DataOneTheme("thigh","бедро"))
    dataTheme.add(DataOneTheme("waist","талия"))
    dataTheme.add(DataOneTheme("leg","нога"))
    dataTheme.add(DataOneTheme("knee","колено"))
    dataTheme.add(DataOneTheme("foot ","ступня "))
    dataTheme.add(DataOneTheme("heel","пятка"))
    dataTheme.add(DataOneTheme("finger","палец"))
    dataTheme.add(DataOneTheme("fingernail","ноготь"))
    dataTheme.add(DataOneTheme("toe","палец ноги"))
    dataTheme.add(DataOneTheme("neck","шея"))
    dataTheme.add(DataOneTheme("face","лицо"))
    dataTheme.add(DataOneTheme("nose","нос"))
    dataTheme.add(DataOneTheme("mouth","рот"))
    dataTheme.add(DataOneTheme("lip","губа"))
    dataTheme.add(DataOneTheme("tooth ","зуб"))
    dataTheme.add(DataOneTheme("tongue","язык"))
    dataTheme.add(DataOneTheme("eye","глаз"))
    dataTheme.add(DataOneTheme("eyebrow","бровь"))
    dataTheme.add(DataOneTheme("eyelash","ресница"))
    dataTheme.add(DataOneTheme("pupil","зрачок"))
    dataTheme.add(DataOneTheme("eyelid","веко"))
    dataTheme.add(DataOneTheme("chin","подбородок"))
    dataTheme.add(DataOneTheme("cheek","щека"))
    dataTheme.add(DataOneTheme("forehead","лоб"))
    dataTheme.add(DataOneTheme("hair","волосы"))
    dataTheme.add(DataOneTheme("moustache","усы"))
    dataTheme.add(DataOneTheme("beard","борода"))
    dataTheme.add(DataOneTheme("appearance","внешность"))
    dataTheme.add(DataOneTheme("thin","худой"))
    dataTheme.add(DataOneTheme("fat","толстый"))
    dataTheme.add(DataOneTheme("tall","высокий"))
    dataTheme.add(DataOneTheme("short","невысокий"))
    dataTheme.add(DataOneTheme("weak","слабый"))
    dataTheme.add(DataOneTheme("strong","сильный"))
    dataTheme.add(DataOneTheme("slim","стройный"))
    dataTheme.add(DataOneTheme("plump","полный"))
    dataTheme.add(DataOneTheme("old","старый"))
    dataTheme.add(DataOneTheme("young","молодой"))
    dataTheme.add(DataOneTheme("hairy","волосатый"))
    dataTheme.add(DataOneTheme("bald","лысый"))
    dataTheme.add(DataOneTheme("curly","кудрявый"))
    dataTheme.add(DataOneTheme("pretty","красивая"))
    dataTheme.add(DataOneTheme("handsome","красивый"))
    dataTheme.add(DataOneTheme("ugly","уродливый"))
    dataTheme.add(DataOneTheme("character","характер"))
    dataTheme.add(DataOneTheme("clever","умный"))
    dataTheme.add(DataOneTheme("talented","талантлевый"))
    dataTheme.add(DataOneTheme("active","активный"))
    dataTheme.add(DataOneTheme("creative","творческий"))
    dataTheme.add(DataOneTheme("energetic","энергичный"))
    dataTheme.add(DataOneTheme("stupid","глупый"))
    dataTheme.add(DataOneTheme("considerate","внимательный"))
    dataTheme.add(DataOneTheme("cruel","жестокий"))
    dataTheme.add(DataOneTheme("unkind","злой"))
    dataTheme.add(DataOneTheme("polite","вежливый"))
    dataTheme.add(DataOneTheme("rude","грубый"))
    dataTheme.add(DataOneTheme("kind","добрый"))
    dataTheme.add(DataOneTheme("tactful","тактичный"))
    dataTheme.add(DataOneTheme("married","женатый"))
    dataTheme.add(DataOneTheme("single","холостяк"))
    dataTheme.add(DataOneTheme("generous","шедрый"))
    dataTheme.add(DataOneTheme("greedy","жадный"))
    dataTheme.add(DataOneTheme("rich","богатый"))
    dataTheme.add(DataOneTheme("poor","бедный"))
    dataTheme.add(DataOneTheme("emotion","эмоция"))
    dataTheme.add(DataOneTheme("mischievous","озорной"))
    dataTheme.add(DataOneTheme("ecstatic","восторженный"))
    dataTheme.add(DataOneTheme("content","довольный"))
    dataTheme.add(DataOneTheme("bored","скучающий"))
    dataTheme.add(DataOneTheme("shocked","в состоянии шока"))
    dataTheme.add(DataOneTheme("offended","обиженный"))
    dataTheme.add(DataOneTheme("confident","самоуверенный"))
    dataTheme.add(DataOneTheme("happy","счастливый"))
    dataTheme.add(DataOneTheme("hopeful","надеющийся"))
    dataTheme.add(DataOneTheme("curious","любопытный"))
    dataTheme.add(DataOneTheme("excited","взволнованный"))
    dataTheme.add(DataOneTheme("lonely","одинокий"))
    dataTheme.add(DataOneTheme("nervous","нервный"))
    dataTheme.add(DataOneTheme("goofy"," глупый"))
    dataTheme.add(DataOneTheme("scared","испуганный"))
    dataTheme.add(DataOneTheme("sad","грустный"))
    dataTheme.add(DataOneTheme("hungry","голодный"))
    dataTheme.add(DataOneTheme("thirsty","испытывающий жажду"))
    dataTheme.add(DataOneTheme("tired","уставший"))
    dataTheme.add(DataOneTheme("sleepy","сонный"))
    dataTheme.add(DataOneTheme("surprised","удивленый"))
    return dataTheme

}

private fun get2ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("health","здоровье"))
    dataTheme.add(DataOneTheme("allergy","аллергия"))
    dataTheme.add(DataOneTheme("plaster","пластырь"))
    dataTheme.add(DataOneTheme("bloody nose","кровь из носа"))
    dataTheme.add(DataOneTheme("broken arm","сломанная рука"))
    dataTheme.add(DataOneTheme("bruise","синяк"))
    dataTheme.add(DataOneTheme("bump","шишка"))
    dataTheme.add(DataOneTheme("cough","кашель"))
    dataTheme.add(DataOneTheme("cut","порез"))
    dataTheme.add(DataOneTheme("diarrhea","диарея"))
    dataTheme.add(DataOneTheme("fever","жар"))
    dataTheme.add(DataOneTheme("headache","головная боль"))
    dataTheme.add(DataOneTheme("loose tooth","шатающийся зуб"))
    dataTheme.add(DataOneTheme("medicine","лекарство"))
    dataTheme.add(DataOneTheme("runny nose","насморк"))
    dataTheme.add(DataOneTheme("scratch","царапина"))
    dataTheme.add(DataOneTheme("shot","укол"))
    dataTheme.add(DataOneTheme("sick","больной"))
    dataTheme.add(DataOneTheme("sneeze","чиханье"))
    dataTheme.add(DataOneTheme("stomachache","боль в животе"))
    dataTheme.add(DataOneTheme("sunburn","солнечный ожог"))
    dataTheme.add(DataOneTheme("thermometer","градусник"))
    dataTheme.add(DataOneTheme("throw up","тошнота"))
    dataTheme.add(DataOneTheme("toothache","зубная боль"))
    dataTheme.add(DataOneTheme("hygiene","гигиена"))
    dataTheme.add(DataOneTheme("care","уход"))
    return dataTheme

}

private fun get3ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("family","семья"))
    dataTheme.add(DataOneTheme("mother","мама"))
    dataTheme.add(DataOneTheme("father","папа"))
    dataTheme.add(DataOneTheme("parents","родители"))
    dataTheme.add(DataOneTheme("son","сын"))
    dataTheme.add(DataOneTheme("daughter","дочь"))
    dataTheme.add(DataOneTheme("children","дети"))
    dataTheme.add(DataOneTheme("sister","сестра"))
    dataTheme.add(DataOneTheme("brother","брат"))
    dataTheme.add(DataOneTheme("grandmother","бабушка"))
    dataTheme.add(DataOneTheme("grandfather","дедушка"))
    dataTheme.add(DataOneTheme("grandson","внук"))
    dataTheme.add(DataOneTheme("granddaughter","внучка"))
    dataTheme.add(DataOneTheme("aunt","тетя"))
    dataTheme.add(DataOneTheme("uncle","дядя"))
    dataTheme.add(DataOneTheme("niece","племянница"))
    dataTheme.add(DataOneTheme("nephew","племянник"))
    return dataTheme

}

private fun get4ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("house","дом"))
    dataTheme.add(DataOneTheme("apartment","квартира"))
    dataTheme.add(DataOneTheme("room","комната"))
    dataTheme.add(DataOneTheme("bathroom","ванная комната"))
    dataTheme.add(DataOneTheme("balcony","балкон"))
    dataTheme.add(DataOneTheme("bedroom","спальня"))
    dataTheme.add(DataOneTheme("closet","шкаф"))
    dataTheme.add(DataOneTheme("dining room","столовая"))
    dataTheme.add(DataOneTheme("doorbell","дверной звонок"))
    dataTheme.add(DataOneTheme("door","дверь"))
    dataTheme.add(DataOneTheme("upstairs","верхний этаж"))
    dataTheme.add(DataOneTheme("downstairs","подвал"))
    dataTheme.add(DataOneTheme("roof","крыша"))
    dataTheme.add(DataOneTheme("window","окно"))
    dataTheme.add(DataOneTheme("garage","гараж"))
    dataTheme.add(DataOneTheme("hall","зал"))
    dataTheme.add(DataOneTheme("kitchen","кухня"))
    dataTheme.add(DataOneTheme("hallway","коридор"))
    dataTheme.add(DataOneTheme("living room","гостиная"))
    dataTheme.add(DataOneTheme("mailbox","почтовый ящик"))
    dataTheme.add(DataOneTheme("shower","душ"))
    dataTheme.add(DataOneTheme("stairs","лестница"))
    dataTheme.add(DataOneTheme("toilet","туалет"))
    dataTheme.add(DataOneTheme("sofa","диван"))
    dataTheme.add(DataOneTheme("armchair","кресло"))
    dataTheme.add(DataOneTheme("chair","стул"))
    dataTheme.add(DataOneTheme("floor","пол"))
    dataTheme.add(DataOneTheme("rug","ковер"))
    dataTheme.add(DataOneTheme("table","стол"))
    dataTheme.add(DataOneTheme("lamp","лампа"))
    dataTheme.add(DataOneTheme("wall","стена"))
    dataTheme.add(DataOneTheme("curtain","штора"))
    dataTheme.add(DataOneTheme("pillow","подушка"))
    dataTheme.add(DataOneTheme("ceiling","потолок"))
    dataTheme.add(DataOneTheme("painting","картина"))
    dataTheme.add(DataOneTheme("picture"," рисунок"))
    dataTheme.add(DataOneTheme("frame","рама"))
    dataTheme.add(DataOneTheme("fireplace","камин"))
    dataTheme.add(DataOneTheme("bookcase","книжный шкаф"))
    dataTheme.add(DataOneTheme("book","книга"))
    dataTheme.add(DataOneTheme("towel","полотенце"))
    dataTheme.add(DataOneTheme("scale","весы"))
    dataTheme.add(DataOneTheme("shelf","полка"))
    dataTheme.add(DataOneTheme("fan","фен"))
    dataTheme.add(DataOneTheme("mirror","зеркало"))
    dataTheme.add(DataOneTheme("sink","раковина"))
    dataTheme.add(DataOneTheme("bath","ванна"))
    dataTheme.add(DataOneTheme("toothbrush","зубная щетка"))
    dataTheme.add(DataOneTheme("toothpaste","зубная паста"))
    dataTheme.add(DataOneTheme("soap","мыло"))
    dataTheme.add(DataOneTheme("sponge","губка"))
    dataTheme.add(DataOneTheme("comb","расческа"))
    dataTheme.add(DataOneTheme("razor","бритва"))
    dataTheme.add(DataOneTheme("bowl","чаша"))
    dataTheme.add(DataOneTheme("salad bowl","салатница"))
    dataTheme.add(DataOneTheme("tablecloth","скатерть"))
    dataTheme.add(DataOneTheme("saltshaker","солонка"))
    dataTheme.add(DataOneTheme("peppershaker","перечница"))
    dataTheme.add(DataOneTheme("teapot","чайник "))
    dataTheme.add(DataOneTheme("coffeepot","кофейник"))
    dataTheme.add(DataOneTheme("sugar bowl","сахарница"))
    dataTheme.add(DataOneTheme("plate","тарелка"))
    dataTheme.add(DataOneTheme("cup","чашка"))
    dataTheme.add(DataOneTheme("glass","стакан"))
    dataTheme.add(DataOneTheme("fork","вилка"))
    dataTheme.add(DataOneTheme("spoon","ложка"))
    dataTheme.add(DataOneTheme("teaspoon","чайная ложка"))
    dataTheme.add(DataOneTheme("knife","нож"))
    dataTheme.add(DataOneTheme("candlestick","подсвечник"))
    dataTheme.add(DataOneTheme("candle","свеча"))
    dataTheme.add(DataOneTheme("napkin","салфетка"))
    dataTheme.add(DataOneTheme("bed","кровать"))
    dataTheme.add(DataOneTheme("mattress","матрац"))
    dataTheme.add(DataOneTheme("pillowcase","наволочка"))
    dataTheme.add(DataOneTheme("sheet","простыня"))
    dataTheme.add(DataOneTheme("blanket","одеяло"))
    dataTheme.add(DataOneTheme("alarm clock","будильник"))
    dataTheme.add(DataOneTheme("sink","раковина"))
    dataTheme.add(DataOneTheme("sponge","губка"))
    dataTheme.add(DataOneTheme("cabinet","шкаф с ящиками"))
    dataTheme.add(DataOneTheme("microwave","микроволновка"))
    dataTheme.add(DataOneTheme("canister","контейнер"))
    dataTheme.add(DataOneTheme("stove","печь"))
    dataTheme.add(DataOneTheme("burner","конфорка"))
    dataTheme.add(DataOneTheme("oven","духовка"))
    dataTheme.add(DataOneTheme("potholder","прихватка"))
    dataTheme.add(DataOneTheme("toaster","тостер"))
    dataTheme.add(DataOneTheme("cookbook","книга с рецептами"))
    dataTheme.add(DataOneTheme("refrigerator","холодильник"))
    dataTheme.add(DataOneTheme("freezer","морозилка"))
    dataTheme.add(DataOneTheme("kitchenware","кухонная посуда"))
    dataTheme.add(DataOneTheme("housekeeping","уборка"))
    dataTheme.add(DataOneTheme("broom","веник"))
    dataTheme.add(DataOneTheme("sweep","подметать"))
    dataTheme.add(DataOneTheme("dustpan","совок для мусора"))
    dataTheme.add(DataOneTheme("vacuum cleaner","пылесос"))
    dataTheme.add(DataOneTheme("iron","утюг"))
    dataTheme.add(DataOneTheme("ironing board","гладильная доска"))
    dataTheme.add(DataOneTheme("mop","швабра"))
    dataTheme.add(DataOneTheme("rag","тряпка"))
    dataTheme.add(DataOneTheme("wipe","мыть"))
    dataTheme.add(DataOneTheme("bleach","отбеливатель"))
    dataTheme.add(DataOneTheme("cleanser","моющее средство"))
    dataTheme.add(DataOneTheme("laundry","стирка"))
    dataTheme.add(DataOneTheme("dust","пыль"))
    dataTheme.add(DataOneTheme("air","проветривать"))
    dataTheme.add(DataOneTheme("trash can","мусорное ведро"))
    dataTheme.add(DataOneTheme("empty","вытряхивать"))
    dataTheme.add(DataOneTheme("garbage","мусор"))
    dataTheme.add(DataOneTheme("dirt","грязь"))
    dataTheme.add(DataOneTheme("shelving","стеллаж"))
    dataTheme.add(DataOneTheme("interior","интерьер"))
    return dataTheme

}

private fun get5ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("transport","транспорт"))
    dataTheme.add(DataOneTheme("ambulance","скорая помощь"))
    dataTheme.add(DataOneTheme("bus","автобус"))
    dataTheme.add(DataOneTheme("car","автомобиль"))
    dataTheme.add(DataOneTheme("helicopter","вертолет"))
    dataTheme.add(DataOneTheme("motorcycle","мотоцикл"))
    dataTheme.add(DataOneTheme("road","дорога"))
    dataTheme.add(DataOneTheme("boat","лодка"))
    dataTheme.add(DataOneTheme("sailboat","парусник"))
    dataTheme.add(DataOneTheme("ship","корабль"))
    dataTheme.add(DataOneTheme("street","улица"))
    dataTheme.add(DataOneTheme("subway","тоннель"))
    dataTheme.add(DataOneTheme("traffic light","светофор"))
    dataTheme.add(DataOneTheme("train","поезд"))
    dataTheme.add(DataOneTheme("van","фургон"))
    dataTheme.add(DataOneTheme("scooter","скутер"))
    dataTheme.add(DataOneTheme("bicycle","велосипед"))
    dataTheme.add(DataOneTheme("airport","аэропорт"))
    dataTheme.add(DataOneTheme("airplane","самолет"))
    dataTheme.add(DataOneTheme("wing","крыло"))
    dataTheme.add(DataOneTheme("tail","хвост"))
    dataTheme.add(DataOneTheme("cabin","салон самолета"))
    dataTheme.add(DataOneTheme("fuselage","корпус самолета"))
    dataTheme.add(DataOneTheme("undercarriage","шасси"))
    dataTheme.add(DataOneTheme("lavatory","туалет"))
    dataTheme.add(DataOneTheme("window","окно"))
    dataTheme.add(DataOneTheme("aisle","проход"))
    dataTheme.add(DataOneTheme("seat"," место"))
    dataTheme.add(DataOneTheme("armrest","подлокотник"))
    dataTheme.add(DataOneTheme("ticket","билет"))
    dataTheme.add(DataOneTheme("suitcase","чемодан"))
    dataTheme.add(DataOneTheme("backpack","рюкзак"))
    dataTheme.add(DataOneTheme("baggage","багаж"))
    dataTheme.add(DataOneTheme("life vest","спасательный жилет"))
    dataTheme.add(DataOneTheme("carry-on","ручная кладь"))
    dataTheme.add(DataOneTheme("flight","рейс"))
    dataTheme.add(DataOneTheme("takeoff","взлет"))
    dataTheme.add(DataOneTheme("landing","посадка"))
    dataTheme.add(DataOneTheme("gate","выход "))
    dataTheme.add(DataOneTheme("boarding","посадка "))
    dataTheme.add(DataOneTheme("passenger","пассажир"))
    dataTheme.add(DataOneTheme("passport","паспорт"))
    dataTheme.add(DataOneTheme("visa","виза"))
    dataTheme.add(DataOneTheme("customs","таможня"))
    dataTheme.add(DataOneTheme("terminal","терминал"))
    dataTheme.add(DataOneTheme("schedule","расписание"))
    dataTheme.add(DataOneTheme("security guard","охранник"))
    dataTheme.add(DataOneTheme("trolley","тележка"))
    dataTheme.add(DataOneTheme("liquid","жидкость"))
    dataTheme.add(DataOneTheme("hijack","угон самолета"))
    dataTheme.add(DataOneTheme("emergency","авария"))
    dataTheme.add(DataOneTheme("delay","задержка"))
    dataTheme.add(DataOneTheme("destination","место назначения"))
    dataTheme.add(DataOneTheme("agency","агентство"))
    dataTheme.add(DataOneTheme("gasoline","бензин"))
    dataTheme.add(DataOneTheme("currency","валюта"))
    dataTheme.add(DataOneTheme("train station","вокзал"))
    dataTheme.add(DataOneTheme("city","город"))
    dataTheme.add(DataOneTheme("guest house","гостевой дом"))
    dataTheme.add(DataOneTheme("hotel","гостиница"))
    dataTheme.add(DataOneTheme("vacation","отпуск"))
    dataTheme.add(DataOneTheme("abroad","за границей"))
    dataTheme.add(DataOneTheme("foreigner","иностранец"))
    dataTheme.add(DataOneTheme("map","карта"))
    dataTheme.add(DataOneTheme("resort","курорт"))
    dataTheme.add(DataOneTheme("route","маршрут "))
    dataTheme.add(DataOneTheme("room","номер"))
    dataTheme.add(DataOneTheme("rest","отдых"))
    dataTheme.add(DataOneTheme("postcard","открытка"))
    dataTheme.add(DataOneTheme("beach","пляж"))
    dataTheme.add(DataOneTheme("coast","побережье"))
    dataTheme.add(DataOneTheme("journey","путешествие"))
    dataTheme.add(DataOneTheme("recreation","развлечение"))
    dataTheme.add(DataOneTheme("capital","столица"))
    dataTheme.add(DataOneTheme("country","страна"))
    dataTheme.add(DataOneTheme("taxi","такси"))
    dataTheme.add(DataOneTheme("exotic","экзотический"))
    return dataTheme

}

private fun get6ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("size","размер"))
    dataTheme.add(DataOneTheme("small","маленький"))
    dataTheme.add(DataOneTheme("big","большой"))
    dataTheme.add(DataOneTheme("medium","средний"))
    dataTheme.add(DataOneTheme("little","маленький"))
    dataTheme.add(DataOneTheme("huge","огромный"))
    dataTheme.add(DataOneTheme("long","длинный"))
    dataTheme.add(DataOneTheme("short","короткий"))
    dataTheme.add(DataOneTheme("wide","широкий"))
    dataTheme.add(DataOneTheme("narrow","узкий"))
    dataTheme.add(DataOneTheme("tall","высокий"))
    dataTheme.add(DataOneTheme("low","низкий"))
    dataTheme.add(DataOneTheme("deep","глубокий"))
    dataTheme.add(DataOneTheme("shallow","мелкий"))
    dataTheme.add(DataOneTheme("thick","толстый"))
    dataTheme.add(DataOneTheme("thin","тонкий"))
    dataTheme.add(DataOneTheme("far","далекий"))
    dataTheme.add(DataOneTheme("near","близкий"))
    return dataTheme

}

private fun get7ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("food"," еда"))
    dataTheme.add(DataOneTheme("ham","ветчина"))
    dataTheme.add(DataOneTheme("sausage","колбаса"))
    dataTheme.add(DataOneTheme("meat","мясо"))
    dataTheme.add(DataOneTheme("egg","яйцо"))
    dataTheme.add(DataOneTheme("pizza","пицца"))
    dataTheme.add(DataOneTheme("soup","суп"))
    dataTheme.add(DataOneTheme("bread","хлеб"))
    dataTheme.add(DataOneTheme("porridge","каша"))
    dataTheme.add(DataOneTheme("flour","мука"))
    dataTheme.add(DataOneTheme("garlic","чеснок"))
    dataTheme.add(DataOneTheme("salad","салат"))
    dataTheme.add(DataOneTheme("fish","рыба"))
    dataTheme.add(DataOneTheme("chicken","цыпленок"))
    dataTheme.add(DataOneTheme("pork","свинина"))
    dataTheme.add(DataOneTheme("beef","говядина"))
    dataTheme.add(DataOneTheme("steak"," стейк"))
    dataTheme.add(DataOneTheme("spice","специя"))
    dataTheme.add(DataOneTheme("butter","масло"))
    dataTheme.add(DataOneTheme("macaroni","макароны"))
    dataTheme.add(DataOneTheme("cheese","сыр"))
    dataTheme.add(DataOneTheme("rice","рис"))
    dataTheme.add(DataOneTheme("pasta","паста"))
    dataTheme.add(DataOneTheme("ketchup","кетчуп"))
    dataTheme.add(DataOneTheme("sauce","соус"))
    dataTheme.add(DataOneTheme("mayonnaise","майонез"))
    dataTheme.add(DataOneTheme("bean","фасоль"))
    dataTheme.add(DataOneTheme("pepper","перец"))
    dataTheme.add(DataOneTheme("salt","соль"))
    dataTheme.add(DataOneTheme("sandwich","бутерброд"))
    dataTheme.add(DataOneTheme("cutlet","котлета"))
    dataTheme.add(DataOneTheme("caviar","икра"))
    dataTheme.add(DataOneTheme("vegetables","овощи"))
    dataTheme.add(DataOneTheme("fruit","фрукт"))
    dataTheme.add(DataOneTheme("baked","печеный"))
    dataTheme.add(DataOneTheme("fried","жареный"))
    dataTheme.add(DataOneTheme("jam","варенье"))
    dataTheme.add(DataOneTheme("sugar","сахар"))
    dataTheme.add(DataOneTheme("candy","конфета"))
    dataTheme.add(DataOneTheme("cake"," торт"))
    dataTheme.add(DataOneTheme("cookie","печенье"))
    dataTheme.add(DataOneTheme("croissant","круассан"))
    dataTheme.add(DataOneTheme("jelly","желе"))
    dataTheme.add(DataOneTheme("ice cream","мороженое"))
    dataTheme.add(DataOneTheme("pancake","блин"))
    dataTheme.add(DataOneTheme("pie","пирог"))
    dataTheme.add(DataOneTheme("sweet","сладкий "))
    dataTheme.add(DataOneTheme("bitter","горький "))
    dataTheme.add(DataOneTheme("salted","соленый"))
    dataTheme.add(DataOneTheme("sour","кислый "))
    dataTheme.add(DataOneTheme("drink","напиток"))
    dataTheme.add(DataOneTheme("beverage","напиток"))
    dataTheme.add(DataOneTheme("water","вода"))
    dataTheme.add(DataOneTheme("lemonade","лимонад"))
    dataTheme.add(DataOneTheme("tea","чай"))
    dataTheme.add(DataOneTheme("coffee","кофе"))
    dataTheme.add(DataOneTheme("juice","сок"))
    dataTheme.add(DataOneTheme("milk","молоко"))
    dataTheme.add(DataOneTheme("cocoa","какао"))
    dataTheme.add(DataOneTheme("chocolate","горячий шоколад"))
    dataTheme.add(DataOneTheme("cocktail","коктейль"))
    dataTheme.add(DataOneTheme("milkshake","молочный коктейль"))
    dataTheme.add(DataOneTheme("iced tea","холодный чай"))
    dataTheme.add(DataOneTheme("orange juice","апельсиновый сок"))
    dataTheme.add(DataOneTheme("tomato juice","томатный сок"))
    dataTheme.add(DataOneTheme("fruit juice","фруктовый сок"))
    dataTheme.add(DataOneTheme("vegetable juice","овощной сок"))
    dataTheme.add(DataOneTheme("alcohol","алкоголь"))
    dataTheme.add(DataOneTheme("alcoholic beverage","алкогольные напитки"))
    dataTheme.add(DataOneTheme("beer","пиво"))
    dataTheme.add(DataOneTheme("wine","вино"))
    dataTheme.add(DataOneTheme("apricot","абрикос"))
    dataTheme.add(DataOneTheme("pineapple","ананас"))
    dataTheme.add(DataOneTheme("banana","банан"))
    dataTheme.add(DataOneTheme("bergamot","бергамот"))
    dataTheme.add(DataOneTheme("grape","виноград"))
    dataTheme.add(DataOneTheme("grapefruit","грейпфрут"))
    dataTheme.add(DataOneTheme("pear","груша"))
    dataTheme.add(DataOneTheme("melon","дыня"))
    dataTheme.add(DataOneTheme("lemon","лимон"))
    dataTheme.add(DataOneTheme("mandarin","мандарин"))
    dataTheme.add(DataOneTheme("peach","персик"))
    dataTheme.add(DataOneTheme("plum","слива"))
    dataTheme.add(DataOneTheme("apple","яблоко"))
    dataTheme.add(DataOneTheme("lime","лайм"))
    dataTheme.add(DataOneTheme("kiwi","киви"))
    dataTheme.add(DataOneTheme("fig","инжир"))
    dataTheme.add(DataOneTheme("mango","манго"))
    dataTheme.add(DataOneTheme("persimmon","хурма"))
    dataTheme.add(DataOneTheme("pomelo","помело"))
    dataTheme.add(DataOneTheme("berry","ягода"))
    dataTheme.add(DataOneTheme("watermelon","арбуз"))
    dataTheme.add(DataOneTheme("barberry","барбарис"))
    dataTheme.add(DataOneTheme("cowberry","брусника"))
    dataTheme.add(DataOneTheme("cherry","вишня"))
    dataTheme.add(DataOneTheme("blackberry","ежевика"))
    dataTheme.add(DataOneTheme("strawberry","клубника"))
    dataTheme.add(DataOneTheme("cranberry","клюква"))
    dataTheme.add(DataOneTheme("raspberry","малина"))
    dataTheme.add(DataOneTheme("blueberry","черника"))
    dataTheme.add(DataOneTheme("sea-buckthorn","облепиха"))
    dataTheme.add(DataOneTheme("currant","смородина "))
    dataTheme.add(DataOneTheme("vegetable","овощ"))
    dataTheme.add(DataOneTheme("basil","базилик"))
    dataTheme.add(DataOneTheme("eggplant","баклажаны"))
    dataTheme.add(DataOneTheme("bean","бобы"))
    dataTheme.add(DataOneTheme("pea","горох"))
    dataTheme.add(DataOneTheme("cabbage","капуста"))
    dataTheme.add(DataOneTheme("potato","картофель"))
    dataTheme.add(DataOneTheme("onion","лук"))
    dataTheme.add(DataOneTheme("carrot","морковь"))
    dataTheme.add(DataOneTheme("cucumber","огурец"))
    dataTheme.add(DataOneTheme("pepper","перец"))
    dataTheme.add(DataOneTheme("parsley","петрушка"))
    dataTheme.add(DataOneTheme("tomato","помидор"))
    dataTheme.add(DataOneTheme("radish","редис"))
    dataTheme.add(DataOneTheme("beet","свекла"))
    dataTheme.add(DataOneTheme("celery","сельдерей"))
    dataTheme.add(DataOneTheme("pumpkin","тыква"))
    dataTheme.add(DataOneTheme("dill","укроп"))
    dataTheme.add(DataOneTheme("haricot","фасоль"))
    dataTheme.add(DataOneTheme("garlic","чеснок"))
    dataTheme.add(DataOneTheme("sorrel","щавель"))
    return dataTheme

}

private fun get8ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("sun","солнце"))
    dataTheme.add(DataOneTheme("sunset"," закат"))
    dataTheme.add(DataOneTheme("sunrise","рассвет"))
    dataTheme.add(DataOneTheme("dew","роса"))
    dataTheme.add(DataOneTheme("waterfall","водопад"))
    dataTheme.add(DataOneTheme("rain","дождь"))
    dataTheme.add(DataOneTheme("lightning","молния"))
    dataTheme.add(DataOneTheme("thunder","гром"))
    dataTheme.add(DataOneTheme("rainbow","радуга"))
    dataTheme.add(DataOneTheme("sky","небо"))
    dataTheme.add(DataOneTheme("cloud","облако"))
    dataTheme.add(DataOneTheme("snow","снег"))
    dataTheme.add(DataOneTheme("ice","лед"))
    dataTheme.add(DataOneTheme("icicle","сосулька"))
    dataTheme.add(DataOneTheme("hoarfrost","иней"))
    dataTheme.add(DataOneTheme("eclipse","затмение"))
    dataTheme.add(DataOneTheme("flood","наводнение"))
    dataTheme.add(DataOneTheme("earthquake","землетрясение"))
    dataTheme.add(DataOneTheme("wind","ветер"))
    dataTheme.add(DataOneTheme("storm","ураган"))
    dataTheme.add(DataOneTheme("nature","природа"))
    dataTheme.add(DataOneTheme("beach"," пляж"))
    dataTheme.add(DataOneTheme("desert","пустыня"))
    dataTheme.add(DataOneTheme("glacier","ледник"))
    dataTheme.add(DataOneTheme("forest","лес"))
    dataTheme.add(DataOneTheme("field","поле"))
    dataTheme.add(DataOneTheme("canyon","каньон"))
    dataTheme.add(DataOneTheme("island","остров"))
    dataTheme.add(DataOneTheme("jungle","джунгли"))
    dataTheme.add(DataOneTheme("lake","озеро"))
    dataTheme.add(DataOneTheme("mountain","гора"))
    dataTheme.add(DataOneTheme("hill","холм"))
    dataTheme.add(DataOneTheme("plain","равнина"))
    dataTheme.add(DataOneTheme("hollow","низина"))
    dataTheme.add(DataOneTheme("pond","пруд"))
    dataTheme.add(DataOneTheme("rock","скала"))
    dataTheme.add(DataOneTheme("ocean","океан"))
    dataTheme.add(DataOneTheme("sea","море"))
    dataTheme.add(DataOneTheme("river","река"))
    dataTheme.add(DataOneTheme("weather","погода"))
    dataTheme.add(DataOneTheme("sunny","солнечный"))
    dataTheme.add(DataOneTheme("cold","холод"))
    dataTheme.add(DataOneTheme("heat","жара"))
    dataTheme.add(DataOneTheme("mist","легкий туман"))
    dataTheme.add(DataOneTheme("fog","туман"))
    dataTheme.add(DataOneTheme("cool","прохладный"))
    dataTheme.add(DataOneTheme("shower","ливень"))
    dataTheme.add(DataOneTheme("lightning","молния"))
    dataTheme.add(DataOneTheme("breeze","легкий ветерок"))
    dataTheme.add(DataOneTheme("rainfall","осадки"))
    dataTheme.add(DataOneTheme("snowfall","снегопад"))
    dataTheme.add(DataOneTheme("hail","град"))
    dataTheme.add(DataOneTheme("bright","ясный"))
    dataTheme.add(DataOneTheme("hot","жаркий"))
    dataTheme.add(DataOneTheme("windy","ветренный"))
    dataTheme.add(DataOneTheme("cloudy","облачный"))
    dataTheme.add(DataOneTheme("rainy","дождливый"))
    dataTheme.add(DataOneTheme("chilly","прохладный"))
    dataTheme.add(DataOneTheme("frosty","морозный"))
    dataTheme.add(DataOneTheme("temperature","температура"))
    return dataTheme

}

private fun get9ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("aquamarine","аквамарин"))
    dataTheme.add(DataOneTheme("beige","бежевый"))
    dataTheme.add(DataOneTheme("snowy","белоснежный"))
    dataTheme.add(DataOneTheme("white","белый"))
    dataTheme.add(DataOneTheme("turquoise","бирюзовый"))
    dataTheme.add(DataOneTheme("pale","бледный"))
    dataTheme.add(DataOneTheme(" bordeaux","бордовый"))
    dataTheme.add(DataOneTheme("bronze","бронзовый"))
    dataTheme.add(DataOneTheme("yellow green","желто-зеленый"))
    dataTheme.add(DataOneTheme("yellow","желтый"))
    dataTheme.add(DataOneTheme("pearl","жемчужный"))
    dataTheme.add(DataOneTheme("green","зеленый"))
    dataTheme.add(DataOneTheme("goldenrod","золотистый"))
    dataTheme.add(DataOneTheme(" golden","золотой"))
    dataTheme.add(DataOneTheme("emerald","изумрудный"))
    dataTheme.add(DataOneTheme("indigo","индиго"))
    dataTheme.add(DataOneTheme("firebrick","кирпичный"))
    dataTheme.add(DataOneTheme("coral","коралловый"))
    dataTheme.add(DataOneTheme("brown","коричневый"))
    dataTheme.add(DataOneTheme("red","красный"))
    dataTheme.add(DataOneTheme("cream","кремовый"))
    dataTheme.add(DataOneTheme("azure","лазурный"))
    dataTheme.add(DataOneTheme("lime green","лимонно-зеленый"))
    dataTheme.add(DataOneTheme("lemon","лимонный"))
    dataTheme.add(DataOneTheme("salmon","лососевый"))
    dataTheme.add(DataOneTheme("raspberry","малиновый"))
    dataTheme.add(DataOneTheme("copper","медный"))
    dataTheme.add(DataOneTheme("honeydew","медовый"))
    dataTheme.add(DataOneTheme("aqua","морская волна"))
    dataTheme.add(DataOneTheme("sky blue","небесно-голубой"))
    dataTheme.add(DataOneTheme("olive","оливковый"))
    dataTheme.add(DataOneTheme("orange","оранжевый"))
    dataTheme.add(DataOneTheme("sienna","охра"))
    dataTheme.add(DataOneTheme("ash","пепельно-серый"))
    dataTheme.add(DataOneTheme("peach","персиковый"))
    dataTheme.add(DataOneTheme("sand-coloured","песочный"))
    dataTheme.add(DataOneTheme("purple","пурпурный"))
    dataTheme.add(DataOneTheme("pink","розовый"))
    dataTheme.add(DataOneTheme("light-green","салатовый"))
    dataTheme.add(DataOneTheme("light","светлый"))
    dataTheme.add(DataOneTheme("silvery","серебряный"))
    dataTheme.add(DataOneTheme("grey","серый"))
    dataTheme.add(DataOneTheme("blue","синий"))
    dataTheme.add(DataOneTheme("lilac","сиреневый"))
    dataTheme.add(DataOneTheme("plum","сливовый"))
    dataTheme.add(DataOneTheme("ivory","слоновая кость"))
    dataTheme.add(DataOneTheme("steel gray","стальной серый"))
    dataTheme.add(DataOneTheme("maroon","темно-бордовый"))
    dataTheme.add(DataOneTheme("dark","темный"))
    dataTheme.add(DataOneTheme("navy-blue","темно-синий"))
    dataTheme.add(DataOneTheme("terracotta","терракотовый"))
    dataTheme.add(DataOneTheme("dull","тусклый"))
    dataTheme.add(DataOneTheme("purple","фиолетовый"))
    dataTheme.add(DataOneTheme("violet","фиолетовый"))
    dataTheme.add(DataOneTheme("pistachio","фисташковый"))
    dataTheme.add(DataOneTheme("magenta","фуксин"))
    dataTheme.add(DataOneTheme("fuchsia","фуксия"))
    dataTheme.add(DataOneTheme("khaki","хаки"))
    dataTheme.add(DataOneTheme("seagreen","морская волна"))
    dataTheme.add(DataOneTheme("black","черный"))
    dataTheme.add(DataOneTheme("amber","янтарный"))
    return dataTheme

}

private fun get10ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("clothes","одежда"))
    dataTheme.add(DataOneTheme("blouse","блузка"))
    dataTheme.add(DataOneTheme("skirt","юбка"))
    dataTheme.add(DataOneTheme("dress","платье"))
    dataTheme.add(DataOneTheme("shirt","рубашка"))
    dataTheme.add(DataOneTheme("trousers","брюки"))
    dataTheme.add(DataOneTheme("socks","носки"))
    dataTheme.add(DataOneTheme("stockings","чулки"))
    dataTheme.add(DataOneTheme("tights","колготки"))
    dataTheme.add(DataOneTheme("swimsuit","купальник"))
    dataTheme.add(DataOneTheme("underpants","нижнее белье"))
    dataTheme.add(DataOneTheme("sweater","свитер"))
    dataTheme.add(DataOneTheme("cardigan","шерстяная кофта"))
    dataTheme.add(DataOneTheme("jersey","вязаный свитер"))
    dataTheme.add(DataOneTheme("suit","костюм"))
    dataTheme.add(DataOneTheme("jeans","джинсы"))
    dataTheme.add(DataOneTheme("shorts","шорты"))
    dataTheme.add(DataOneTheme("t-shirt","футболка"))
    dataTheme.add(DataOneTheme("cap","кепка"))
    dataTheme.add(DataOneTheme("hat","шляпа"))
    dataTheme.add(DataOneTheme("shoes","туфли"))
    dataTheme.add(DataOneTheme("boots","ботинки"))
    dataTheme.add(DataOneTheme("sneakers","кроcсовки"))
    dataTheme.add(DataOneTheme("slippers","тапочки"))
    dataTheme.add(DataOneTheme("sandals","сандали"))
    dataTheme.add(DataOneTheme("jacket","куртка"))
    dataTheme.add(DataOneTheme("coat","пальто"))
    dataTheme.add(DataOneTheme("raincoat","плащ"))
    dataTheme.add(DataOneTheme("fur coat","шуба"))
    dataTheme.add(DataOneTheme("belt","ремень"))
    dataTheme.add(DataOneTheme("tie","галстук"))
    dataTheme.add(DataOneTheme("glove","перчатка"))
    dataTheme.add(DataOneTheme("scarf","шарф"))
    dataTheme.add(DataOneTheme("nightie","ночнушка"))
    dataTheme.add(DataOneTheme("pyjama","пижама"))
    dataTheme.add(DataOneTheme("tracksuit","спортивный костюм"))
    dataTheme.add(DataOneTheme("anorak","куртка с капюшоном"))
    dataTheme.add(DataOneTheme("dungarees","рабочие штаны"))
    dataTheme.add(DataOneTheme("umbrella","зонт"))
    dataTheme.add(DataOneTheme("watch","часы"))
    dataTheme.add(DataOneTheme("earring","сережка"))
    dataTheme.add(DataOneTheme("ring","кольцо"))
    dataTheme.add(DataOneTheme("necklace","колье"))
    dataTheme.add(DataOneTheme("bracelet","браслет"))
    dataTheme.add(DataOneTheme("glasses","очки"))
    return dataTheme

}

private fun get11ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("pet","домашнее животное"))
    dataTheme.add(DataOneTheme("cat","кот"))
    dataTheme.add(DataOneTheme("kitten","котенок"))
    dataTheme.add(DataOneTheme("dog","собака"))
    dataTheme.add(DataOneTheme("puppy","щенок"))
    dataTheme.add(DataOneTheme("hamster","хомяк"))
    dataTheme.add(DataOneTheme("guinea pig","морская свинка"))
    dataTheme.add(DataOneTheme("farm","ферма"))
    dataTheme.add(DataOneTheme("chicken","курица"))
    dataTheme.add(DataOneTheme("rooster","петух"))
    dataTheme.add(DataOneTheme("turkey","индюк"))
    dataTheme.add(DataOneTheme("goat","козел"))
    dataTheme.add(DataOneTheme("kid","козленок"))
    dataTheme.add(DataOneTheme("sheep","овца"))
    dataTheme.add(DataOneTheme("lamb","барашек"))
    dataTheme.add(DataOneTheme("bull","бык"))
    dataTheme.add(DataOneTheme("cow","корова"))
    dataTheme.add(DataOneTheme("calf","теленок"))
    dataTheme.add(DataOneTheme("horse","лошадь"))
    dataTheme.add(DataOneTheme("pig","свинья"))
    dataTheme.add(DataOneTheme("piglet","поросенок"))
    dataTheme.add(DataOneTheme("rabbit","кролик"))
    dataTheme.add(DataOneTheme("animal","животное"))
    dataTheme.add(DataOneTheme("bear","медведь"))
    dataTheme.add(DataOneTheme("fox","лиса"))
    dataTheme.add(DataOneTheme("rabbit","заяц"))
    dataTheme.add(DataOneTheme("wolf","волк"))
    dataTheme.add(DataOneTheme("pig","кабан"))
    dataTheme.add(DataOneTheme("deer","олень"))
    dataTheme.add(DataOneTheme("moose","лось"))
    dataTheme.add(DataOneTheme("donkey","осел"))
    dataTheme.add(DataOneTheme("buffalo","зубр"))
    dataTheme.add(DataOneTheme("camel","верблюд"))
    dataTheme.add(DataOneTheme("giraffe","жираф"))
    dataTheme.add(DataOneTheme("hippopotamus","бегемот"))
    dataTheme.add(DataOneTheme("zebra","зебра"))
    dataTheme.add(DataOneTheme("kangaroo","кенгуру"))
    dataTheme.add(DataOneTheme("elephant","слон"))
    dataTheme.add(DataOneTheme("llama","лама"))
    dataTheme.add(DataOneTheme("foal","жеребенок"))
    dataTheme.add(DataOneTheme("armadillo","броненосец"))
    dataTheme.add(DataOneTheme("leopard","леопард"))
    dataTheme.add(DataOneTheme("lion","лев"))
    dataTheme.add(DataOneTheme("tiger","тигр"))
    dataTheme.add(DataOneTheme("bison","бизон"))
    dataTheme.add(DataOneTheme("koala","коала"))
    dataTheme.add(DataOneTheme("hyena","гиена"))
    dataTheme.add(DataOneTheme("panda","панда"))
    dataTheme.add(DataOneTheme("rhinoceros","носорог"))
    dataTheme.add(DataOneTheme("monkey","обезьяна"))
    dataTheme.add(DataOneTheme("gorilla","горилла"))
    dataTheme.add(DataOneTheme("chimpanzee","шимпанзе"))
    dataTheme.add(DataOneTheme("gibbon","гиббон"))
    dataTheme.add(DataOneTheme("baboon","бабуин"))
    dataTheme.add(DataOneTheme("anteater","муравьед"))
    dataTheme.add(DataOneTheme("mouse","мышь"))
    dataTheme.add(DataOneTheme("possum","опоссум"))
    dataTheme.add(DataOneTheme("skunk","скунс"))
    dataTheme.add(DataOneTheme("bat","летучая мышь"))
    dataTheme.add(DataOneTheme("beaver","бобер"))
    dataTheme.add(DataOneTheme("gopher","суслик"))
    dataTheme.add(DataOneTheme("squirrel","белка"))
    dataTheme.add(DataOneTheme("rat","крыса"))
    dataTheme.add(DataOneTheme("chipmunk","бурундук"))
    dataTheme.add(DataOneTheme("porcupine","дикобраз"))
    dataTheme.add(DataOneTheme("raccoon","енот"))
    dataTheme.add(DataOneTheme("coral","коралл"))
    dataTheme.add(DataOneTheme("seal","тюлень"))
    dataTheme.add(DataOneTheme("crocodile","крокодил"))
    dataTheme.add(DataOneTheme("alligator","аллигатор"))
    dataTheme.add(DataOneTheme("fish","рыба"))
    dataTheme.add(DataOneTheme("trout","форель"))
    dataTheme.add(DataOneTheme("bass","окунь"))
    dataTheme.add(DataOneTheme("salmon","лосось"))
    dataTheme.add(DataOneTheme("flounder","камбала"))
    dataTheme.add(DataOneTheme("swordfish","рыба-меч"))
    dataTheme.add(DataOneTheme("eel","угорь"))
    dataTheme.add(DataOneTheme("otter","выдра"))
    dataTheme.add(DataOneTheme("walrus","морж"))
    dataTheme.add(DataOneTheme("mussel","мидия"))
    dataTheme.add(DataOneTheme("snail","улитка"))
    dataTheme.add(DataOneTheme("shrimp","креветка"))
    dataTheme.add(DataOneTheme("oyster","устрица"))
    dataTheme.add(DataOneTheme("lobster","омар"))
    dataTheme.add(DataOneTheme("crab","краб"))
    dataTheme.add(DataOneTheme("crayfish","речной рак"))
    dataTheme.add(DataOneTheme("shark","акула"))
    dataTheme.add(DataOneTheme("jellyfish","медуза"))
    dataTheme.add(DataOneTheme("sea urchin","морской еж"))
    dataTheme.add(DataOneTheme("whale","кит"))
    dataTheme.add(DataOneTheme("frog","лягушка"))
    dataTheme.add(DataOneTheme("turtle","черепаха"))
    dataTheme.add(DataOneTheme("dolphin","дельфин"))
    dataTheme.add(DataOneTheme("sea snake","морская змея"))
    dataTheme.add(DataOneTheme("mollusc","моллюск"))
    dataTheme.add(DataOneTheme("shellfish","ракообразное"))
    dataTheme.add(DataOneTheme("seafood","морепродукты"))
    dataTheme.add(DataOneTheme("octopus","осьминог"))
    dataTheme.add(DataOneTheme("cachalot","кашалот"))
    dataTheme.add(DataOneTheme("starfish","морская звезда"))
    dataTheme.add(DataOneTheme("bird","птица"))
    dataTheme.add(DataOneTheme("robin","дрозд"))
    dataTheme.add(DataOneTheme("jay","сойка"))
    dataTheme.add(DataOneTheme("hummingbird","колибри"))
    dataTheme.add(DataOneTheme("pheasant","фазан"))
    dataTheme.add(DataOneTheme("crow","ворона"))
    dataTheme.add(DataOneTheme("flamingo","фламинго"))
    dataTheme.add(DataOneTheme("seagull","чайка"))
    dataTheme.add(DataOneTheme("sparrow","воробей"))
    dataTheme.add(DataOneTheme("woodpecker","дятел"))
    dataTheme.add(DataOneTheme("swallow","ласточка"))
    dataTheme.add(DataOneTheme("pigeon","голубь"))
    dataTheme.add(DataOneTheme("owl","сова"))
    dataTheme.add(DataOneTheme("hawk","сокол"))
    dataTheme.add(DataOneTheme("eagle","орел"))
    dataTheme.add(DataOneTheme("canary","канарейка"))
    dataTheme.add(DataOneTheme("cuckoo","кукушка"))
    dataTheme.add(DataOneTheme("cockatoo","какаду"))
    dataTheme.add(DataOneTheme("parrot","попугай"))
    dataTheme.add(DataOneTheme("duck","утка"))
    dataTheme.add(DataOneTheme("goose","гусь"))
    dataTheme.add(DataOneTheme("swan","лебедь"))
    dataTheme.add(DataOneTheme("crane","журавль"))
    dataTheme.add(DataOneTheme("stork","аист"))
    dataTheme.add(DataOneTheme("pelican","пеликан"))
    dataTheme.add(DataOneTheme("peacock","павлин"))
    dataTheme.add(DataOneTheme("penguin","пингвин"))
    dataTheme.add(DataOneTheme("ostrich","страус"))
    dataTheme.add(DataOneTheme("insect","насекомое"))
    dataTheme.add(DataOneTheme("fly","муха"))
    dataTheme.add(DataOneTheme("mosquito","комар"))
    dataTheme.add(DataOneTheme("flea","блоха"))
    dataTheme.add(DataOneTheme("firefly","светлячок"))
    dataTheme.add(DataOneTheme("moth","моль"))
    dataTheme.add(DataOneTheme("dragonfly","стрекоза"))
    dataTheme.add(DataOneTheme("spider","паук"))
    dataTheme.add(DataOneTheme("ladybug","божья коровка"))
    dataTheme.add(DataOneTheme("wasp","оса"))
    dataTheme.add(DataOneTheme("tick","клещ"))
    dataTheme.add(DataOneTheme("bee","пчела"))
    dataTheme.add(DataOneTheme("caterpillar","гусеница"))
    dataTheme.add(DataOneTheme("butterfly","бабочка"))
    dataTheme.add(DataOneTheme("ant","муравей"))
    dataTheme.add(DataOneTheme("grasshopper","кузнечик"))
    dataTheme.add(DataOneTheme("beetle","жук"))
    dataTheme.add(DataOneTheme("termite","термит"))
    dataTheme.add(DataOneTheme("roach","таракан"))
    dataTheme.add(DataOneTheme("scorpion","скорпион"))
    dataTheme.add(DataOneTheme("centipede","многоножка"))
    dataTheme.add(DataOneTheme("mantis","богомол"))
    dataTheme.add(DataOneTheme("cricket","сверчок"))
    dataTheme.add(DataOneTheme("bug","жук"))
    dataTheme.add(DataOneTheme("worm","червяк"))
    return dataTheme

}

private fun get12ThemeData():ArrayList<DataOneTheme>{
    val dataTheme= arrayListOf<DataOneTheme>()
    dataTheme.add(DataOneTheme("action","действие"))
    dataTheme.add(DataOneTheme("walk","идти"))
    dataTheme.add(DataOneTheme("run","бежать"))
    dataTheme.add(DataOneTheme("march","маршировать"))
    dataTheme.add(DataOneTheme("crawl","ползать"))
    dataTheme.add(DataOneTheme("drag","тянуть"))
    dataTheme.add(DataOneTheme("pull"," тащить"))
    dataTheme.add(DataOneTheme("push","толкать"))
    dataTheme.add(DataOneTheme("jump","прыгать"))
    dataTheme.add(DataOneTheme("skip"," скакать"))
    dataTheme.add(DataOneTheme("leap","прыжок"))
    dataTheme.add(DataOneTheme("hop","подпрыгивать"))
    dataTheme.add(DataOneTheme("hit","ударять "))
    dataTheme.add(DataOneTheme("slap","шлепать"))
    dataTheme.add(DataOneTheme("kick","удар ногой"))
    dataTheme.add(DataOneTheme("stretch","тянуться"))
    dataTheme.add(DataOneTheme("lift"," поднимать"))
    dataTheme.add(DataOneTheme("put","ставить"))
    dataTheme.add(DataOneTheme("lean"," опирать"))
    dataTheme.add(DataOneTheme("dive","нырять"))
    dataTheme.add(DataOneTheme("sit","сидеть"))
    dataTheme.add(DataOneTheme("squat","приседание"))
    dataTheme.add(DataOneTheme("bend","сгибаться"))
    dataTheme.add(DataOneTheme("hold","держать"))
    dataTheme.add(DataOneTheme("carry"," носить"))
    dataTheme.add(DataOneTheme("catch","ловить"))
    dataTheme.add(DataOneTheme("throw","бросать"))
    return dataTheme

}